# create-react-doc configuration.

# Site
title: Create React Doc

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
## todo: auto menu
menu: [
  docs/快速上手.md,
  docs/更新日志.md,
  docs/主题,
  docs/站点发布.md,
  docs/Front-matter.md,
  docs/数学公式.md,
  docs/书写组件.md,
  docs/高阶用法.md,
  docs/其它工具.md,
  docs/测试
]
## set init open menu keys
# menuOpenKeys:

# site theme
devTheme: packages/crd-seed/index
# theme: crd-seed

# Github
## if you want to editing pages on github, you should config these arguments.
user: MuYunyun
repo: create-react-doc
github-ribbons: true
domain: https://muyunyun.cn
seo:
  google: true

# Available values: en | zh-cn
language: en

# Inject Custom Logic
inject: injectLogic/index.js

# Use abbrlink
abbrlink: true

# Show Tags in head
tags: true

# Config comment section
comment:
  # Giscus Config, The config parameter that's supported can be seen in [giscus-component](https://github.com/giscus/giscus-component#documentation).
  GiscusConfig:
    repoId: MDEwOlJlcG9zaXRvcnkyNjgwMTE4MzA=
