# create-react-doc configuration, see https://github.com/MuYunyun/create-react-doc##config.yml

# Site
title: Create React Doc

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
## todo: auto menu
menu: docs/快速上手.md,docs/默认主题.md,docs/站点发布.md,docs/高阶用法.md,docs/自定义主题.md,docs/其它工具.md,docs/更新日志.md,aaa
## set init open menu keys
# menuOpenKeys:

# site theme
devTheme: packages/crd-seed/index
# theme: crd-seed

# Github
## if you want to editing pages on github, you should config these arguments.
user: MuYunyun
repo: create-react-doc
github-ribbons: true

# Available values: en | zh-cn
language: en

# Inject Custom Logic
inject: injectLogic/index.js