# create-react-doc configuration, see https://github.com/MuYunyun/create-react-doc##config.yml

# Site
title: Create React Doc

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
menu: packages/templates/default/Introduction
## set init open menu keys
# menuOpenKeys:

# site theme
theme: crd-seed

# Github
## if you want to editing pages on github, you should config these arguments.
user: MuYunyun
repo: create-react-doc
branch: main              # the default value of branch is main
deploy_branch: gh-pages   # which branch to deploy.(default: gh-pages)
# publish:                # if you want upload to gitlab or other git platform, you can set full git url in it

# use search plugin: provide ability for searching site globally in the site.
# default value: true
search: true
host: 'muyunyun.cn'            # the url host to search
search_map: {                  # search_map is connected to menu props
  '/packages/templates/default/Introduction': 'Introduction'
}

# Available values: en | zh-cn
language: en