# create-react-doc configuration, see https://github.com/MuYunyun/create-react-doc##config.yml

# Site
title: Create React Doc

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
menu: Introduction
## set init open menu keys
# menuOpenKeys:

# Github
## if you want to editing pages on github, you should config these arguments.
# user:
# repo:
branch: master            # the default value of branch is master
deploy_branch: gh-pages   # which branch to deploy.(default: gh-pages)
# publish:                # if you want upload to gitlab or other git platform, you can set full git url in it

# Available values: en | zh-cn
language: en